{{- if not .Values.database.existingSecret }}
{{- $secretName := printf "%s-mysql" (include "fleetdm.fullname" .) }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "fleetdm.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{- if $existingSecret }}
  {{ .Values.database.passwordKey }}: {{ index $existingSecret.data .Values.database.passwordKey }}
  mysql-root-password: {{ index $existingSecret.data "mysql-root-password" }}
  {{- else }}
  {{ .Values.database.passwordKey }}: {{ randAlphaNum 32 | b64enc | quote }}
  mysql-root-password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}
{{- if and .Values.cache.usePassword (not .Values.cache.existingSecret) }}
{{- $redisSecretName := printf "%s-redis" (include "fleetdm.fullname" .) }}
{{- $existingRedisSecret := lookup "v1" "Secret" .Release.Namespace $redisSecretName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $redisSecretName }}
  labels:
    {{- include "fleetdm.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{- if $existingRedisSecret }}
  {{ .Values.cache.passwordKey }}: {{ index $existingRedisSecret.data .Values.cache.passwordKey }}
  {{- else }}
  {{ .Values.cache.passwordKey }}: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}
