{{- if not .Values.database.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fleetdm.fullname" . }}-mysql
  labels:
    {{- include "fleetdm.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{ .Values.database.passwordKey }}: {{ randAlphaNum 32 | b64enc | quote }}
  mysql-root-password: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
{{- if and .Values.cache.usePassword (not .Values.cache.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fleetdm.fullname" . }}-redis
  labels:
    {{- include "fleetdm.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{ .Values.cache.passwordKey }}: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
